-- Q1. What is the total revenue generated by male vs female customers?

select gender, sum(`Purchase Amount (USD)`) revenue
from customer_shopping_behavior
group by Gender order by Gender;

-- Q2. Which customer used a discount but still spent more than the average purchase amount?

select `ï»¿Customer ID`, `Purchase Amount (USD)`
from customer_shopping_behavior
where `Discount Applied` = "Yes" and `Purchase Amount (USD)` >= (select AVG(`Purchase Amount (USD)`)
from customer_shopping_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?

select `Item Purchased`, round(avg(`Review Rating`), 2) "Average Ratings"
from customer_shopping_behavior
group by `Item Purchased`
order by avg(`Review Rating`) desc
limit 5;

-- Q4. Compare the average purchase amounts between standard and express shipping.

select avg(`Purchase Amount (USD)`), `Shipping Type`
from customer_shopping_behavior
where `Shipping Type` in ("Express", "Standard")
group by `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between 
-- subscribers and non-subscribers.

select `Subscription Status`, count(`ï»¿Customer ID`) "Total Customers",
round(avg(`Purchase Amount (USD)`)) "Average Spend", round(sum(`Purchase Amount (USD)`)) "Total Revenue"
from customer_shopping_behavior
group by `Subscription Status`
order by "Total Revenue", "Average Spend" desc;

-- Q6.  Which 5 products have the highest percentage of purchases with discounts applied?

select `Item Purchased`,
round(sum(case when `Discount Applied` = "Yes" then 1 else 0 end)/count(*) * 100, 2) "Discount Rate"
from customer_shopping_behavior
group by `Item Purchased`
order by "Discount Rate" desc
limit 5;

-- Q7. Segment customer into new, returning and loyal based on their total number of previous
-- purchases, and show the count of each segment.

-- with customer_type as (
-- select `ï»¿Customer ID`, `Previous Purchases`,
-- case
-- when `Previous Purchases` = 1 then 'New'
-- when `Previous Purchases` between 1 and 10 then 'Returning'
-- else 'Loyal'
-- end as customer_segment
-- from customer_shopping_behavior
-- )

-- Q8. What are the top three most purchased products within each category?

-- with item_counts as (
-- select Category,
-- `Item Purchased`,
-- count(`ï»¿Customer ID`) "Total Orders"

-- )

-- Q9. Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select `Subscription Status`,
count(`ï»¿Customer ID`) "Repeat Buyers"
from customer_shopping_behavior
where `Previous Purchases` > 5
group by `Subscription Status`;

-- Q10. What is the revenue contribution of each age group?

select Age,
sum(`Purchase Amount (USD)`) "Total Revenue"
from customer_shopping_behavior
group by Age
order by "Total Revenue";